name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./webapp
    steps:
      # Check out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        
      # Set up git config and submodule
      - name: Set git config & submodule
        run: |
          git config --local user.email "serenita15@gmail.com"
          git config --local user.name "dannamachi"

      # Push to repo connected to azure
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERS_TOKEN }}
        with:
          source-directory: 'webapp'
          destination-github-username: 'dannamachi'
          destination-repository-name: 'msa-2021-ai-project-webapp'
          user-email: serenita15@gmail.com
          target-branch: main
